mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from views import welcome
from restaurants.views import menu, list_restaurants, comment
from views import login, index, logout


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^menu/$', menu),
	url(r'^welcome/$', welcome),
	url(r'^restaurants_list/$', list_restaurants),
	url(r'^comment/(\d{1,5})/$', comment),
	url(r'^accounts/login/$', login),
	url(r'^index/$', index),
	url(r'^accounts/logout/$', logout),
)

restaurants/models.py
from django.db import models

class Restaurant(models.Model):
	name = models.CharField(max_length=20)
	phone_number = models.CharField(max_length=15)
	address = models.CharField(max_length=50, blank=True)
	
	def __unicode__(self):
		return self.name

class Food(models.Model):
	name = models.CharField(max_length=20)
	price = models.DecimalField(max_digits=3, decimal_places=0)
	comment = models.CharField(max_length=50, blank=True)
	is_spicy = models.BooleanField(default=False)
	restaurant = models.ForeignKey(Restaurant)
	
	def __unicode__(self):
		return self.name

class Comment(models.Model):
	content = models.CharField(max_length=225)
	visitor = models.CharField(max_length=225)
	email = models.EmailField(max_length=225)
	date_time = models.DateTimeField()
	restaurant = models.ForeignKey(Restaurant)
	

restaurants/forms.py
from django import forms

class CommentForm(forms.Form):
	visitor = forms.CharField(max_length=20)
	email = forms.CharField(max_length=20, required=False)
	content = forms.CharField(max_length=200, widget=forms.Textarea())

mysite/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django import template
from django.http import HttpResponse
from django.contrib import auth
from django.template import RequestContext
from django.http import HttpResponseRedirect

def menu(request):
	food = {'name':'tomato', 'price':60, 'comment':'goodtoeat', 'is_spicy':False }
	
	food2 = {'name':'pea', 'price': 80, 'comment' : 'notbad', 'is_spicy':True}
	foods = [food,food2]
	return render_to_response('menu.html', locals())

def welcome(request):
	if 'user_name' in request.GET and request.GET['user_name'] !='':
		return HttpResponse('Welcome!~'+request.GET['user_name'])
	else:
		return render_to_response('welcome.html', locals())
		
def login(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect('/index/')
	
	username = request.POST.get('username', '')
	password = request.POST.get('password', '')

	user = auth.authenticate(username=username, password=password)
	
	if user is not None and user.is_active:
		auth.login(request, user)
		return HttpResponseRedirect('/index/')
	else:
		return render_to_response('login.html', RequestContext(request, locals()))
		
def index(request):
	return render_to_response('index.html', RequestContext(request, locals()))
	
def logout(request):
	auth.logout(request)
	return HttpResponseRedirect('/index/')

restaurants/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django import template
from django.http import HttpResponse
from restaurants.models import Restaurant, Food, Comment
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.template import RequestContext
from restaurants.forms import CommentForm

def menu(request):
	if 'id' in request.GET and request.GET['id'] != '':
		restaurant = Restaurant.objects.get(id=request.GET['id'])
		return render_to_response('menu.html', locals())
	else:
		return HttpResponseRedirect("/restaurants_list/")
	
def list_restaurants(request):
	restaurants = Restaurant.objects.all()
	return render_to_response('restaurants_list.html', locals())
	
def comment(request,id):
	if id:
		r = Restaurant.objects.get(id=id)
	else:
		return HttpResponseRedirect("/restaurants_list/")
	errors = []
	if request.POST:
		visitor = request.POST['visitor']
		content = request.POST['content']
		email = request.POST['email']
		date_time = timezone.localtime(timezone.now()) #目前時間
		if any(not request.POST[k] for k in request.POST):
			errors.append('*有空白欄位，請不要留空白')
		if '@' not in email:
			errors.append('* email格式不正確，請重新輸入')
		if not errors:
			Comment.objects.create(
				visitor=visitor,
				email=email,
				content=content,
				date_time=date_time,
				restaurant=r
				)
			visitor, email, content = ('', '', '')
	f = CommentForm()
	return render_to_response('comments.html', RequestContext(request, locals()))

	

restaurants/templates/comments.html
<html>
	<head>
		<title> Comments </title>	
		<meta charset='utf-8'>
	</head>	
	<body>
	  <h2>{{ r.name }}的評價</h2>
        {% if r.comment_set.all %}
        <p>目前共有{{ r.comment_set.all|length }}條評價</p>
        <table >
            <tr>
                <th>留言者</th>
                <th>時間</th>
                <th>評價</th>
            </tr>
            {% for c in r.comment_set.all %}
            <tr>
                <td> {{ c.visitor }} </td>
                <td> {{ c.date_time | date:"F j, Y" }} </td>
                <td> {{ c.content }} </td>
            </tr>
            {% endfor %}
        </table>
		{% else %}
        <p>無評價</p>
        {% endif %}

        <br /><br />
		{% for e in errors %}
			<p style="color:red;">{{ e }}</p>
		{% endfor %}
		
		 <form action="" method="post"> {% csrf_token %}
		 <table>
			{{f.as_table}}
		 </table>
		 <input type="submit" value="給予評價">
		 </form>
	</body>
</html>

restaurants/templates/menu.html
<html>
	<head>
		<title> Menu </title>
		<meta charset="utf-8" />
	</head>
	<body>
		<h2>{{ restaurant.name }}的Menu</h2>
		{% if restaurant.food_set.all %}
		<p>本餐廳共有{{ restaurant.food_set.all|length}} 道菜</p>
		<table>
			<tr>
				<th>菜名</th>
				<th>價格</th>
				<th>辣不辣</th>
				<th>註解</th>
			</tr>
			{% for food in restaurant.food_set.all %}
			<tr>
				<td>{{food.name}}</td>
				<td>{{food.price}}</td>
				<td>{%if food.is_spicy%} 辣 {% else %}
										不辣{% endif %}</td>
				<td>{{food.comment}}</td>
			</tr>
			{% endfor %}
		</table>
		 {% else %}
		 <p>本餐廳什麼都沒賣</p>
		 {% endif %}
	</body>
</html>

restaurants/templates/welcome.html
<html>
	<head>
		<title> Welcome </title>	
	</head>	
	<body>
		<form action="" method="get">
			<label for ="user_name">您的名字</label>
			<input id="user_name" type="text" name="user_name">
			<input type ="submit" value="進入網站">
		</form>
	</body>
</html>

templates/index.html
<html>
	<head>
		<title> Restaurant King </title>	
		<meta charset="utf-8">
	</head>	
	<body>
		<h2>歡迎來到餐廳王</h2>
		{% if request.user.is_authenticated %}
		<p>
			{{request.user}} 您已經登入嚕~
			<a href="/accounts/logout/">登出</a>
		</p>
		<a href="/restaurants_list/">餐廳列表</a>
		{% else %}
			<p>您尚未登入喔~<a href="/accounts/login/">登入</a></p>
		{% endif %}
	</body>
</html>

templates/login.html
<html>
	<head>
		<title> Login </title>	
	</head>	
	<body>
	  <form action="" method="post">
		<label for="username">用戶名稱:</label>{% csrf_token %}
		<input type="text" name = "username" value = "{{username}}" id="username"> <br /> </input>
		<label for="password">用戶密碼:</label>
		<input type="password" name = "password" value = "" id="password"> <br /> </input>
		<input type="submit" value = "登入" ></input>
	  </form>
	</body>
</html>

templates/restaurants_list.html
<html>
	<head>
		<title> Restaurant </title>	
		<meta charset='utf-8'>
	</head>	
	<body>
		<h2>餐廳列表</h2>
		<form action="/menu/" method="get">
		<table>
			<tr>
				<th>選取</th>
				<th>店名</th>
				<th>電話</th>
				<th>地址</th>
				<th>評價</th>
			</tr>
			{% for r in restaurants %}
			<tr>
				<td><input type="radio" name="id" value="{{r.id}}"></td>
				<td>{{ r.name }}</td>
				<td>{{ r.phone_number }}</td>
				<td>{{ r.address }}</td>
				<td><a href="/comment/{{r.id}}/">評論</a></td>
			</tr>
			{% endfor %}
		</table>
		<input type="submit" value="觀看menu">
		</form>
	</body>
</html>

templates/welcome.html
<html>
	<head>
		<title> Welcome </title>	
	</head>	
	<body>
		<form action="/welcome/" method="get">
			<label for ="user_name">您的名字</label>
			<input id="user_name" type="text" name="user_name">
			<input type ="submit" value="進入網站">
		</form>
	</body>
</html>